### ISSUE TITLE
Sortable polymorphic many to many, inverse relationship sorting?

### ISSUE THREAD

**Issue by timganter** [boxfrommars/rutorika-sortable#16]
Hello!

First off, this is fantastic plugin! It works really well. Thanks for building it!

I was trying to do the inverse of what you had in your example. http://sortable5.boxfrommars.ru/posts

Rather than sorting tags within a post. Is it possible to sort posts within a tag? I couldn't figure out if that was possible. 

Thanks again!
-Tim

**Comment by boxfrommars** [comment]
@timganter Hello! Thank you :)
can you provide your current database structure?

**Comment by timganter** [comment]
@boxfrommars Sure! I'm going to email it to you if you don't mind. Just don't want to post it here where it's public since it's client work. =)

**Comment by boxfrommars** [comment]
@timganter Got it. Yes, your structure is almost the same as in the demo. Do you need sorting both tags and posts? If you don't, solution is:

1. Remove `BelongsToSortedManyTrait` and replace `->belongsToSortedMany` with default `->belongsToMany` in the your `Post` model
2. Add to the `Tag` model:
```php
   use BelongsToSortedManyTrait;

    public function posts()
    {
        return $this->belongsToSortedMany('\App\Post');
    }
```

Note, that now you should use
```php
    $tag->posts()->save($posts);
    $tag->posts()->attach($posts->id);
    $tag->posts()->sync([$postId1, $postId2, /* ...postIds */]);
```
instead of `$post->tags()->...`

**Comment by timganter** [comment]
@boxfrommars Thanks Dmitry. 

I gave that a shot. I'm using polymorphic relations. So, in my Post model I have...

```php
public function tag()
    {
        return $this->morphedByMany(Tag::class, 'taggable')->withTimestamps();
    }
```

In my Tag model I have...

```php
public function post()
    {
        return $this->morphToSortedMany(Post::class, 'taggable')->withTimestamps();
    }
```

However I'm getting an SQL error. 

```sql
Column not found: 1054 Unknown column 'post_id' in 'field li
  st' (SQL: select `post_id` from `taggables` where `taggable_id` = 2 and `taggable_type` = App\Tag)
```

Did I hook things up correctly?

Thanks again for your help!

**Comment by boxfrommars** [comment]
@timganter Sorry for waiting.
I've added `->morphedBySortedMany` relation and demo for it: http://sortable5.boxfrommars.ru/albums-and-videos

So you need add to your `Tag` model `MorphToSortedManyTrait` trait and this relation: (like in the https://github.com/boxfrommars/rutorika-sortable-demo5/blob/master/app/Author.php)
```php
use Rutorika\Sortable\MorphToSortedManyTrait;

class Tag extends Model
{
    use MorphToSortedManyTrait;

    public function posts()
    {
        return $this->morphedBySortedMany('App\Post', 'taggable', 'position');
    }
}
```
and then you can attach/sync/save posts to this tag (not vice versa):
```php
$tag->posts()->save($posts);
$tag->posts()->attach($posts->id);
$tag->posts()->sync([$postId1, $postId2, /* ...postIds */]);
```

I'll update readme in a few days (I'm on vacation now)

**Comment by boxfrommars** [comment]
@timganter I've forgot to say, you should update the package to the version 3.1.0 for this functionality

**Comment by timganter** [comment]
@boxfrommars So cool! Thanks again man! =)
