### ISSUE TITLE
Mass update positions on a model

### ISSUE THREAD

**Issue by hassankhan** [boxfrommars/rutorika-sortable#17]
Is there any way to receive an sorted array of ids and use that to update the position on each row?

**Comment by boxfrommars** [comment]
Yes, you can, something like
```php
$posts = Post::sorted()->get()
$position = 1;
foreach ($posts as $post) {
    $post->position = $position;
    $post->save();
    $position++;
}
```
Note, that it may be slow if you have a lot of rows.

Also you can do it with SQL:
```sql
SET @position = 0;
UPDATE posts SET position = (@position := @position + 1) ORDER BY position ASC;
```

But i think it's not necessary to update positions, see #7

**Comment by hassankhan** [comment]
I'm receiving an array of `ids[]` from a request:

```php
        $positions = array_flip($request->input('item_ids'));
        foreach($items->all() as $item) {
            $item->update(['position' => $positions[$item->id] + 1]);
        }
        return response()->redirectToRoute($item->getTable().'.index');
```

I was hoping there was a way to do it without using a for loop :)

**Comment by boxfrommars** [comment]
@hassankhan Oh, understood. 
I see only one improvement: You can update positions without retrieving items:
```php
foreach ($positions as $id => $position) {
    DB::update('UPDATE items SET position = ? where id = ?', [$position, $id]);
}
```
But you should be careful, because no events will be fired
