### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::siblingssiblings()

### ISSUE THREAD

**Issue by fonz-lu** [boxfrommars/rutorika-sortable#18]
Hi,

I'm using the "Sortable many to many" and everything works as expected.

My database structure is like the one you gave in the readme. But I am sorting the posts and not the categories (tags).

When I display all the posts for one tag, everything works. Sorting works. Added post gets the correct position. etc.

What I want to do next is when I display one post, I to want to display within that page a link to the previous and next post. But the next() or previous() function gives me the following exception:
```Call to undefined method Illuminate\Database\Query\Builder::siblingssiblings()```
when I try $post->next(); (Controller or view)
and 
```
Illegal operator and value combination.
/vendor/rutorika/sortable/src/Rutorika/Sortable/SortableTrait.php
     * @return QueryBuilder
     */
    public function siblings($isNext, $limit = 0)
    {
        $sortableField = static::getSortableField();
 
        $query = static::applySortableGroup($this->newQuery(), $this);
        $query->where($sortableField, $isNext ? '>' : '<', $this->getAttribute($sortableField));
        $query->orderBy($sortableField, $isNext ? 'asc' : 'desc');
        if ($limit !== 0) {
```
when I try $post->previous();

Here are my models:

Post model
```
class Faq_post extends Model
{
  
    use \Rutorika\Sortable\SortableTrait;
    use \Rutorika\Sortable\SortableTrait;
    public function categories()
     {
        return $this->belongsToSortedMany('App\Faq_category', 'position','faq_posts_faq_categories');
     }
```

Categories mode:
```
class Faq_category extends Node
{
    use BelongsToSortedManyTrait;

    public function posts() {
        return $this->belongsToSortedMany('\App\Faq_post', 'position', 'faq_posts_faq_categories');
    }
```

Am I missing something? Thank you

**Comment by boxfrommars** [comment]
First of all you don't need `belonsToSortedMany` relation in the `Faq_post` (you cannot order both categories and posts with the same column `position`). Also you don't need `\Rutorika\Sortable\SortableTrait` in the `Faq_post`, this trait is for 'plane' sorting only (not for sorting through relations). Therefore you can't use `$post->next()` to get next post in your category. I think you can get next post with something like
```
$post->category->posts()->where('position', '>', $post->position)->first();
```
and previous post with
```
$post->category->posts()->where('position', '<', $post->position)->last();
```

**Comment by boxfrommars** [comment]
@fonz-lu First of all you don't need `belonsToSortedMany` relation in the `Faq_post` (you cannot order both categories and posts with the same column `position`). Also you don't need `\Rutorika\Sortable\SortableTrait` in the `Faq_post`, this trait is for 'plane' sorting only (not for sorting through relations). Therefore you can't use `$post->next()` to get next post in your category. I think you can get next post with something like
```
$post->category->posts()->where('position', '>', $post->position)->first();
```
and previous post with
```
$post->category->posts()->where('position', '<', $post->position)->last();

**Comment by fonz-lu** [comment]
Ok thanks, I will try

Shouldn't the line 141 in SortableTrait.php be 
```
return $this->siblings(true, $limit);
```
instead of 
```
return $this->siblingssiblings(true, $limit);
```

**Comment by boxfrommars** [comment]
@fonz-lu Hmm, may be you accidentally change the file? Because in the repository it's ok with this file: https://github.com/boxfrommars/rutorika-sortable/blob/master/src/Rutorika/Sortable/SortableTrait.php#L150

**Comment by fonz-lu** [comment]
Yes, I think a changed that by accident.

I am using Baum with this example https://github.com/etrepat/baum/wiki/Example:-Products-and-categories

I moved away from the pivot table and now I am using the grouped method of sortable. The post model now uses the SortableTrait, but next() and previous() still doesn't work. I did use something you posted above and everything works as expected.

Thank you

**Comment by boxfrommars** [comment]
@fonz-lu Note that `->next()` and `->previous()` returns `QueryBuilder`, so if you want to get a collection of posts or post you should do
```
$post->next(1)->get();
// and
$post->previous(1)->get();

//or
$post->getNext(1);
// and
$post->getPrevious(1);
```
