### ISSUE TITLE
"entityClass":["The entity class field is required."]

### ISSUE THREAD

**Issue by rudolphp** [boxfrommars/rutorika-sortable#19]
I get this error after drag and drop. The entity name is what I gave in config/sortable.php 
```
return [
    'entities' => [
        'pages' => '\App\Pages'
    ]
```
Is there some other config needed. I don't see this error message in the source code so I can debug.

**Comment by boxfrommars** [comment]
@rudolphp this error means that there is no class `\App\Pages` in your app. May be it's a typo and you class is `\App\Page`?

**Comment by rudolphp** [comment]
@boxfrommars thank you that error is gone, and now I do get a "success" message, but the position column is not getting updated in the db.

**Comment by boxfrommars** [comment]
@rudolphp what request did you send?

**Comment by rudolphp** [comment]
@boxfrommars It works thanks!. On another note, can the grouping be done with a parentID in the same table as in the article table. So I would have a parent article and under it many child articles.

**Comment by boxfrommars** [comment]
@rudolphp yes, i think.
