### ISSUE TITLE
Sorting Pivot tables

### ISSUE THREAD

**Issue by YOzaz** [boxfrommars/rutorika-sortable#2]
Hey - would it be possible to extend this package for sorting relationships through pivot tables?
I have a many-to-many relation through pivot, and need sorting to be there...

**Comment by boxfrommars** [comment]
you should add position field to your pivot table, then create model for pivot table, and add SortableTrait to this model. Now you can move entities with `moveBefore` and `moveAfter`. Also you can modify jquery UI example (replace `data-itemId="{{{ $article->id }}}"` with `data-itemId="{{{ $article->pivot->id }}}"` and change model in `rutorika/sortable/config.php` to `PivotModel`)

but i dont know what about autogenerated position on create. i need to check it.

**Comment by YOzaz** [comment]
@boxfrommars thanks for reply. But I believe it would require a little bit more than that - like in example here: http://stackoverflow.com/a/24247952

**Comment by jrean** [comment]
Hi, before going deeper @YOzaz did you find a solution?
I need the exact same logic!

--

I try to understand how can I use it for `pivot` tables?
I have a Venue and an Event model. A Venue can have many Event(s) and an Event belongToMany Venue(s). So I have the pivot table but no Eloquent Model...
For each Venue, I would like to display the attached Event(s) and being able to manage Event(s) order for that Venue. I should keep track of Event position within the pivot table, right?

So the pivot table should look the following: `:id ; :venue_id ; :event_id ; :position`

**Comment by boxfrommars** [comment]
@jrean I think approach at stackoverflow link posted by @YOzaz is the right way. i'll try to implement it today

**Comment by jrean** [comment]
I will dig into it so! Thank you for your fast answer.
Anyway, If you can implement it, I will use your package!
:-)

**Comment by YOzaz** [comment]
@jrean I ended up with separate model, which represents relationship between other two. Not ideal though...

**Comment by jrean** [comment]
@boxfrommars I tried to dig into the stackoverflow link posted but, hum, it is yet to complex for my level, ...
I hope you'll find the time and energy to implement it.
Thank you in advance.

**Comment by boxfrommars** [comment]
@YOzaz @jrean I've added pivot sorting to the package. see readme for docs and http://sortable5.boxfrommars.ru/posts for demo.

**Comment by YOzaz** [comment]
Brilliant! Thanks a lot - but I'll take a look after a month or so only, on holidays at the moment :)

**Comment by jrean** [comment]
@boxfrommars you rock! Thank you :)

Now I have a question, I will open a new issue if needed.

For instance I have a `Serie` and `Episode` tables. A `Serie` has many `Episodes` and an `Episode` belongs to many `Serie`.
I will have a pivot table `serie_episode`.

With your package when I create a new `Episode` it will automatically hydrate the order position. How could we override / extends this behaviours? I want to store `Episode` order for each `Serie` and not for all episodes.

The idea would be to allow to pass a parameter to say if the new `Episode` should be ordered from all episodes or from a given range. In my case I would like it to be ordered regarding all other episodes attached to a given `Serie`.

Same for the `setNewOrder()`. I woud like it to allow to set new order of `Episode` for a given `Serie`.

Do you get the idea? Can we try to refactor?

Thank you again for your fast update.

**Comment by jrean** [comment]
Brillant! Thank you :)
