### ISSUE TITLE
Array to string conversion error if $sortableGroupField is an array

### ISSUE THREAD

**Issue by danielispas** [boxfrommars/rutorika-sortable#20]
I set `protected static $sortableGroupField = ['fieldName1','fieldName2'];` as in documentation and it throwed an array to string conversion exception in SortableTrait.php on line 255. I managed to solve this problem by adding an else after the if with is_array condition and it worked. Here is the code: 
```
public function checkSortableGroupField($sortableGroupField, $entity)
    {
        if ($sortableGroupField === null) {
            return;
        }

        if (is_array($sortableGroupField)) {
            foreach ($sortableGroupField as $field) {
                if ($this->$field !== $entity->$field) {
                    throw new SortableException($this->$field, $entity->$field);
                }
            }
        } else
        
            if ($this->$sortableGroupField !== $entity->$sortableGroupField) {
                throw new SortableException($this->$sortableGroupField, $entity->$sortableGroupField);
            }
    }
```

**Comment by boxfrommars** [comment]
@danielispas what version of the package do you use?

**Comment by danielispas** [comment]
I use 3.1
Composer.json:
`"rutorika/sortable": "^3.1",`

**Comment by boxfrommars** [comment]
I just updated version (3.2.0). I think it has fix for this issue.

**Comment by danielispas** [comment]
I updated and the issue is gone. Thanks for a great project.
