### ISSUE TITLE
Multiple Rows drag and drop

### ISSUE THREAD

**Issue by brealme** [boxfrommars/rutorika-sortable#29]
Is it possible in rutorika sortable package?

**Comment by boxfrommars** [comment]
@brealme Can you explain step by step what do you want?

**Comment by boxfrommars** [comment]
from #26 
> # You can't move entities with different sortable group: 5 4
> 
> i have already two entities and when i am adding third entities in config/sortable.php file after than raised error in third entities 
> first two entities working properly but third is not working and that error raised.
> 
> I want multiple rows drag and drop, is it possible in rutorika-sortable??
> 
> plz give me solution

**Comment by brealme** [comment]
Is there any way to select multiple rows from a single data-table and drag and drop all selected rows to the same data-table and on dropping, i want all rows positions to be updated in the database. Is it possible? if yes, then how?

**Comment by boxfrommars** [comment]
No, multiple rows drag'n'drop isn't supported. But you can write your own Controller which handle нщгк 	
requirements
