### ISSUE TITLE
Laravel 5 compatible?

### ISSUE THREAD

**Issue by wstudios** [boxfrommars/rutorika-sortable#3]
Will this work in Laravel 5 and if not will there be an update?

**Comment by boxfrommars** [comment]
not yet. but i'm going to update the package in a few week

**Comment by vluzrmos** [comment]
Consider my PR #5

**Comment by boxfrommars** [comment]
@wstudios i've merged PR by @vluzrmos, so, now package is L5 compatible

**Comment by vluzrmos** [comment]
:+1:
