### ISSUE TITLE
Laravel 5.4 compatible? 

### ISSUE THREAD

**Issue by ZAZmaster** [boxfrommars/rutorika-sortable#30]
> Class App\Model contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (App\Model ::getBelongsToManyCaller)

**Comment by ZAZmaster** [comment]
Yep, getBelongsToManyCaller is now getRelations
proof https://github.com/corcel/corcel/pull/244/commits/939323f856fa2f2ff33417a977871f412d32ce21

**Comment by ZAZmaster** [comment]
Also getOtherKey method has been renamed to getOwnerKey in 5.4

**Comment by moussaclarke** [comment]
You can replace all instance of getBelongsToManyCaller with getRelations - seems to work although haven't really tested extensively. I could do a pull request for this but would obviously break 5.3 compatibility. Maybe I'll fork it and link here?

**Comment by moussaclarke** [comment]
Here you go:
https://github.com/moussaclarke/rutorika-sortable/commit/1222ff328965fd09586ea0a032e6e7fbb520b924

NB: PHPUnit tests are all failing on my machine, but I think that's related to [this](https://github.com/orchestral/testbench/issues/155) and I don't really have time to look into it

**Comment by moussaclarke** [comment]
And this for the other method that @ZAZmaster mentioned:
https://github.com/moussaclarke/rutorika-sortable/commit/25a7d190d0d6f0a0a883595b39d8a3a351d5ff4b

**Comment by boxfrommars** [comment]
@moussaclarke could you create a pull request with this chnages?

**Comment by SRWieZ** [comment]
https://github.com/troydildine/rutorika-sortable/commits/bugfix
This version is working great in 5.4
@troydildine

**Comment by boxfrommars** [comment]
Laravel 5.4 was added in [version 3.4](https://github.com/boxfrommars/rutorika-sortable/releases/tag/3.4.0). Thank you all!

**Comment by troydildine** [comment]
Thanks @boxfrommars! Appreciate that.
