### ISSUE TITLE
belongsToSortedMany has issue with same values inserted (laravel 5.4)

### ISSUE THREAD

**Issue by rdpascua** [boxfrommars/rutorika-sortable#37]
I'm using `belongsToSortedMany` in the immediate model in `Playlist`.

```php
public function tracks()
{
  return $this
        ->belongsToSortedMany(Track::class, 'position')
        ->withTimestamps();
}
```

What happen is when I perform `moveBefore` or `moveAfter` the position of the `tracks` are all the same.

## After the `move` operation

**playlist_track**

playlist_id | track_id|position
--------------|-------------|--
1|1|2 
1|1|2

**tracks**

id|name
---|----
1|Foo
2|Bar

**playlists**

id|name
---|-----
1|Sample Playlist

**Comment by boxfrommars** [comment]
@rdpascua Is the question still actual? sorry for silence
