### ISSUE TITLE
Cannot save position when drag and drop the table data

### ISSUE THREAD

**Issue by lvc2202** [boxfrommars/rutorika-sortable#38]
There don't have any error and i can get the entity and the position id as well. But I'm not sure why it can't save the position in the database. Pls help me , thank you.

**Comment by lvc2202** [comment]
I realized the movebefore and moveafter didn't save my position data.
Any idea ?

**Comment by boxfrommars** [comment]
what version of laravel and rutorika-sortable do you use?

**Comment by lvc2202** [comment]
rutorika-sortable 3.4 and  laravel 5.4.28

**Comment by lvc2202** [comment]
config/sortable.php

<?php

return [
    'entities' => [
        // 'articles' => '\Article' for simple sorting (entityName => entityModel) or
        // 'articles' => ['entity' => '\Article', 'relation' => 'tags'] for many to many or many to many polymorphic relation sorting
        'scrollquestion' => '\App\Scroll_Question', // entityNameForUseInRequest => ModelName
    ],
];

**Comment by boxfrommars** [comment]
Try to do this in tinker:
```
~/Workspace/your-project$ php artisan tinker
Psy Shell v0.8.9 (PHP 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> $first = \App\Scroll_Question::orderBy('position')->first();
>>> print $first->position;
>>> $second = \App\Scroll_Question::orderBy('position')->offset(1)->first();
>>> print $second->position;
>>> $first->moveAfter($second);
>>> print $first->position;
>>> print $second->position;
```
If all is ok, then positions of first and second entities must be flipped

**Comment by lvc2202** [comment]
This one I should be put in where ? Controller or Model ?

**Comment by boxfrommars** [comment]
in command line
see https://laracasts.com/series/laravel-5-fundamentals/episodes/8 since 1:45

**Comment by lvc2202** [comment]
During this line "$first->moveAfter($second);" , it returns null.
Print $first->position; and print $second->position; return 1 for both

**Comment by boxfrommars** [comment]
ok, undestood. Did you add position behaviour when you already have some data in scroll_questions table?

**Comment by boxfrommars** [comment]
you can fix this with this code in tinker:
```
~/Workspace/your-project$ php artisan tinker
Psy Shell v0.8.9 (PHP 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> DB::table('scroll_questions')->update(['position' => DB::raw('id')]);
```

**Comment by lvc2202** [comment]
But I do this in tinker with this code, it won't help in actual coding for this package right ?

**Comment by lvc2202** [comment]
I think I didn't added the position behavior. I just followed the instruction u wrote.

**Comment by lvc2202** [comment]
This code i have tried but not working. 
~/Workspace/your-project$ php artisan tinker
Psy Shell v0.8.9 (PHP 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 — cli) by Justin Hileman
>>> DB::table('scroll_questions')->update(['position' => DB::raw('id')]);

**Comment by lvc2202** [comment]
$entity = Article::find(1);
$positionEntity = Article::find(10)
$entity->moveAfter($positionEntity);

$article = new Article();
$article->title = $faker->sentence(2);
$article->description = $faker->paragraph();
$article->save();
do I need to add this codes to save to the position ?
If yes, where should I put it ?
And sry for keep bothering you.

**Comment by lvc2202** [comment]
It's working now, I realized that I set my position default value is zero in DB so it can't sort. 
Thank you for helping me so much ^_^
And just to let u know when the position has the same value, it can sort but it can't save the position value.

**Comment by lvc2202** [comment]
If can I suggest you let other user know that position number cannot be the same.
