### ISSUE TITLE
Is it possible to have empty rows

### ISSUE THREAD

**Issue by divyasreem** [boxfrommars/rutorika-sortable#40]
Hi,

I have some requirement  where I can leave some empty rows in between.
Need to store the position of empty row also.

In order to display in particular position.
Please let me know How can I achieve this.

**Comment by boxfrommars** [comment]
What do you mean by empty rows?

**Comment by divyasreem** [comment]
Can you please check the screenshot 
![screen shot 2017-08-03 at 3 15 12 pm](https://user-images.githubusercontent.com/4035450/28916100-b57b8de0-785e-11e7-9207-fc846605308d.png)


Need to relate between two columns

**Comment by boxfrommars** [comment]
i think you need frontend sorting. for example [Sortable](https://github.com/RubaXa/Sortable) or [jQuery UI Sortable](https://jqueryui.com/sortable/)
