### ISSUE TITLE
syncWithoutDetaching does not work properly on belongsToSortedMany relations

### ISSUE THREAD

**Issue by tsufurukawa** [boxfrommars/rutorika-sortable#42]
Hi! I haven't had the chance to really dig into this issue but I noticed that using `syncWithoutDetaching` on a `belongsToSortedMany` relation will simply act as a normal `sync`.

I wasn't sure if the library simply doesn't support `syncWithoutDetaching` or if this is a bug. I can try to investigate further when I have some time but just pointing it out in case anyone had any feedback.

**Comment by boxfrommars** [comment]
@SRWieZ Thank you! I have merged your fix and bump version to 4.1
