### ISSUE TITLE
Database table cannot be found if model is using a specific database connection

### ISSUE THREAD

**Issue by dath** [boxfrommars/rutorika-sortable#43]
If the sortable model is using a specific database connection, its base table cannot be found since the connection name is not considered at the moment.

The validator fails with the following PDOException during calling the sort function of the SortableController:

> PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx' doesn't exist

StackTrace points to

> Rutorika\Sortable\SortableController.php(21): Illuminate\Validation\Validator->passes()

The reason why the table cannot be found is the missing name of the database connection prepended to the table name in the "exists" validation rules.

Also the creation of a new sortable model fails by the same PDOException if no position is set manually.

I have found the corresponding code lines and will provide a fix for this issue in the next days.

**Comment by boxfrommars** [comment]
@dath Thank you! Great work!
