### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by ZAZmaster** [boxfrommars/rutorika-sortable#45]
Hello!

I got error

> Array to string conversion

when use `morphedBySortedMany`

On 5.4 this code work fine.

**Comment by boxfrommars** [comment]
Laravel 5.5 is now supported in [v4.0](https://github.com/boxfrommars/rutorika-sortable/releases/tag/4.0)

**Comment by ZAZmaster** [comment]
But morphedBySortedMany returns an empty collection now :(

**Comment by boxfrommars** [comment]
Hm, i found that there is no tests exists for morphedBySortedMany :( i'll try to fix it today

**Comment by ZAZmaster** [comment]
Any news?

**Comment by ZAZmaster** [comment]
@boxfrommars two months have passed ...))))

**Comment by ZAZmaster** [comment]
I found bug and create pull request https://github.com/boxfrommars/rutorika-sortable/pull/53

**Comment by boxfrommars** [comment]
thank you! sorry for delay. i merged your pull request. see [version 4.2](https://github.com/boxfrommars/rutorika-sortable/releases/tag/4.2)

**Comment by ZAZmaster** [comment]
thank you!
