### ISSUE TITLE
`byPosition` scope

### ISSUE THREAD

**Issue by imam** [boxfrommars/rutorika-sortable#48]
In my application, I'm always creating `byPosition` scope to fetch data by the position. Is there any similar functionality already written? Or may I make one?

**Comment by boxfrommars** [comment]
Yes, you can use `->sorted()` scope

**Comment by boxfrommars** [comment]
From docs:

> To get ordered entities use the sorted scope:
```php
$articles = Article::sorted()->get();
```

**Comment by imam** [comment]
Oh sorry, I think I'm not giving the right context. I mean that we can pass a simple query `byPosition($position)` and then get a single datum in that exact position. For instance, I want to get an article that is in position 3, I just pass that query, and got the result that I wanted.

**Comment by boxfrommars** [comment]
ok, i understood. but it isn't good idea to get entities with the query like this:
```
$query->where('position', $somePosition);
```
because entity with this position can be deleted.

it is better to get for example third entity from start with something like this:
```
$query->sorted()->offset(3)->first();
```

**Comment by imam** [comment]
Sorry for the long response.

How about we create two methods? `byPosition` and `byOffset`?

**Comment by boxfrommars** [comment]
@imam `byOffset` -- ok, (get third entity looks good), But i dont like `byPosition` -- position value is internal value you shouldn't use it in your code.
I'll implement `byOffset` in next release
