### ISSUE TITLE
Confused by Setup

### ISSUE THREAD

**Issue by cvassios-ekko** [boxfrommars/rutorika-sortable#52]
Using Laravel 5.3.31, I ran `composer require rutorika/sortable:3.4.1`, continued through the steps in README, and when I got to 

> Add \Rutorika\Sortable\SortableTrait to your Eloquent model.

I add `use \Rutorika\Sortable\SortableTrait;` to my model and get an error "Trait 'Rutorika\Sortable\SortableTrait' not found". 

I'm lost after this.

**Comment by boxfrommars** [comment]
example of trait usage: https://github.com/boxfrommars/rutorika-sortable-demo5/blob/master/app/Article.php

**Comment by vsuta** [comment]
I had it perfect working in laravel 4.2.

now on laravel 5.5. I get error:

message | The payload is invalid.
-- | --

**Comment by boxfrommars** [comment]
@vsuta Can you show the whole error message?

**Comment by vsuta** [comment]
Hi @boxfrommars I got it to work. It was Token Mismatch, but the laravel throw different error.
It works as expected after ajax setup.
Thank you for  this great package!
