### ISSUE TITLE
Sorting by two group fields

### ISSUE THREAD

**Issue by YOzaz** [boxfrommars/rutorika-sortable#6]
Hey,

I was wondering, how hard it would be to implement sorting by multiple group fields? Suppose it shouldn't be hard:

```php
if ($sortableGroupField)
{
	$query = static::newInstance();
	
	\Illuminate\Support\Collection::make($sortableGroupField)->each(
		function($field) use ($query, $model)
		{
			$query = $query->where($field, $model->$field);
		}
	);
	
	$maxPosition = $query->max('position');
}
```
Similar adjustment can be made for `_applySortableGroup`.
Collection::make() can be moved to `getSortableGroupField` function.
I'm using Laravel 4 package by the way.

**Comment by boxfrommars** [comment]
@YOzaz I think it wouldnt be hard, but I don't see the point to do it now. So if somebody will need this functionality, I implement it, but not now.

**Comment by YOzaz** [comment]
@boxfrommars thanks for paying attention here. In my case, a model is depended on two fields, e.g. a Photo can have a relationship to Post and a Gallery.
In general, this becomes required when you're working with polymorphic relations a lot.

**Comment by giordanolima** [comment]
+1

**Comment by boxfrommars** [comment]
thank you @giordanolima! see version 2.4.0 for this functionality
