### ISSUE TITLE
Laravel 5.7 support?

### ISSUE THREAD

**Issue by wemteqdev** [boxfrommars/rutorika-sortable#65]
is it compatible with laravel 5.7 now?

**Comment by esl51** [comment]
Yes, it is compatible, just checked.

**Comment by mattboban** [comment]
@esl51 unfortunately not as I've just noticed a compatibility issue in BelongsToSortedManyTrait:

> Declaration of Rutorika\Sortable\BelongsToSortedManyTrait::joiningTable($related) must be compatible with Illuminate\Database\Eloquent\Model::joiningTable($related, $instance = NULL)

would oyu accept a PR?

**Comment by esl51** [comment]
> would oyu accept a PR?

I'm not a maintainer of this package.

**Comment by boxfrommars** [comment]
@wemteqdev Yes, version 4.7 of this package is now compatible with laravel 5.7 (thanks @timothyasp and @troydildine)
