### ISSUE TITLE
No Re-Sorting after Delete?

### ISSUE THREAD

**Issue by 7talents** [boxfrommars/rutorika-sortable#7]
Is it something I am missing, or does the trait not re-sort the remaining entries in the database after I delete one or multiple entries by Eloquent ->delete() ?

**Comment by boxfrommars** [comment]
@7talents You are not missing, there is no resort after delete. My approach is that you shouldn't think about `position` values, so you shouldn't worry about gaps in it, because gaps not affect the functionality. But if you want, you can add reposition on delete event. Something like:

```php
// YourAppServiceProvider

YourModel::deleting(function ($model) {
    $model->next()->decrement('position');
});
```
 > You need rutorika-sortable >=1.2.5 to use `->next()`

**Comment by 7talents** [comment]
Great, thank you for the clarification. Did not thinkt about it that way, but now that saying it, I get it that it the value of the position is no neccessarily relevant.

**Comment by boxfrommars** [comment]
I have added this clarification to the readme. Thank you for the question!
