### ISSUE TITLE
Laravel 7 support?

### ISSUE THREAD

**Issue by emco83** [boxfrommars/rutorika-sortable#71]
Currently this plugin doesn't work on Laravel 7.
Any fix available?

**Comment by boxfrommars** [comment]
@emco83 Hi!
I will add support for the new version in the near future (today I think). Thank you for reporting!

**Comment by Magiczne** [comment]
Any update on this?

**Comment by boxfrommars** [comment]
@emco83 @Magiczne 
Hi! Sorry for delay. 
I've just realised version 7.0.0 with Laravel 7 support: https://github.com/boxfrommars/rutorika-sortable/releases/tag/7.0.0

**Comment by Magiczne** [comment]
Thanks a lot!

**Comment by emco83** [comment]
Great job, it's working great!

I have one suggestions: since Laravel 5.5 many plugins are using the automated technique with service providers, which means you won't need to add manually the service provider in config/app.php file.

It would be nice if you create a version with such functionality, so that step with the setup will be skipped.
