### ISSUE TITLE
Is is possible in belongsToSortedMany set a new item position 1 and also reorder other item

### ISSUE THREAD

**Issue by alexpisotsky** [boxfrommars/rutorika-sortable#76]
Sdantard works module, all new items have order number last item + 1.  Is it possible when a new item will be first (has position 1) and other items will be reordered automatically?

**Comment by boxfrommars** [comment]
You can do it by moving new item before the first item. Something like: 
```php
$post->tags()->save($newTag); // add new tag
$firstTag = $post->tags()->first(); // get first tag
$post->tags()->moveBefore($newTag, $firstTag); // move new tag before first tag
```
