### ISSUE TITLE
How to change primaryKey ?

### ISSUE THREAD

**Issue by markpolarisdesign** [boxfrommars/rutorika-sortable#8]
how to change primary key from id to article_id

This is my error.
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'id' in 'where clause' (SQL: select count(*) as aggregate from `articles` where `id` = 2)

Thank you

**Comment by boxfrommars** [comment]
@markpolarisdesign I think I fixed the issue. now you just need to set 
```php
protected $primaryKey = 'article_id';
```
in your model

**Comment by markpolarisdesign** [comment]
![2015-08-26_9-25-01](https://cloud.githubusercontent.com/assets/13967962/9484278/6305d358-4bd4-11e5-9335-b02e45319322.jpg)
![2015-08-26_9-24-35](https://cloud.githubusercontent.com/assets/13967962/9484279/6339da5e-4bd4-11e5-9bb1-d30485d8e901.jpg)

Hahaha...  I tried but same error.

**Comment by markpolarisdesign** [comment]
I try

**Model**
$primaryKey = 'article_id';

**DB primarykey column**
column name = 'article_id';

show error : unknown column 'id'

---

**Model**
$primaryKey = 'article_id';

**DB primarykey column**
column name = 'id';

show error : unknown column 'articles.article_id'

---

**Model**
$primaryKey = 'id';

**DB primarykey column**
column name = 'id';

It's ok 

why ? hahaha

**Comment by markpolarisdesign** [comment]
![2015-08-26_9-52-52](https://cloud.githubusercontent.com/assets/13967962/9484564/3d04e3d4-4bd8-11e5-94d6-46b6a5958229.jpg)

Ok :) It's ok when i create method for sort

**Comment by markpolarisdesign** [comment]
![2015-08-26_9-55-53](https://cloud.githubusercontent.com/assets/13967962/9484595/ad1100cc-4bd8-11e5-9c8d-1256788b2e6b.jpg)

It's ok when i create new method for sort.

**Comment by boxfrommars** [comment]
Yes, because error is in validation, and in you method you don't use validation.

Did you update the package?

```
composer show -i rutorika/sortable
```

It should be 2.3.1

**Comment by boxfrommars** [comment]
All tests are passed
