### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by peterbabic** [boxfrommars/rutorika-sortable#82]
Created a pull request https://github.com/boxfrommars/rutorika-sortable/pull/81

**Comment by YOzaz** [comment]
Now for Laravel 11 too: https://github.com/boxfrommars/rutorika-sortable/pull/84

**Comment by boxfrommars** [comment]
@YOzaz Thank you! Merged in the version [9.2.0](https://github.com/boxfrommars/rutorika-sortable/releases/tag/9.2.0)
